import { $, defineConfig } from "@hey-api/openapi-ts";
import ts from "typescript";

const stringIntFormats = new Set(["int64", "uint64", "int128", "uint128"]);

type TransformerInput = {
  schema: {
    type?: string;
    format?: string;
  };
  dataExpression?: Parameters<typeof $.expr>[0] | string;
};

const stringIntToBigInt = ({ schema, dataExpression }: TransformerInput) => {
  if (schema.type !== "string" || !schema.format || !stringIntFormats.has(schema.format)) return;
  if (dataExpression === undefined) return;

  const bigIntCall = $("BigInt").call($.expr(dataExpression).attr("toString").call());

  if (typeof dataExpression === "string") return [bigIntCall];
  return [$.expr(dataExpression).assign(bigIntCall)];
};

export default defineConfig({
  input: "./openapi.camel.yaml",
  output: {
    // header: ["/* eslint-disable */", "// This file is auto-generated by @hey-api/openapi-ts"],
    path: "src/client",
  },
  plugins: [
    {
      enums: "javascript",
      name: "@hey-api/typescript",
    },
    // ...other plugins
    // In your configuration, add @hey-api/transformers to your plugins and you'll be ready to generate transformers.
    {
      name: "@hey-api/transformers",
      dates: true,
      bigInt: true,
      transformers: [stringIntToBigInt],
      typeTransformers: [
        ({ schema }) => {
          if (schema.type === "string" && schema.format && stringIntFormats.has(schema.format)) {
            return ts.factory.createKeywordTypeNode(ts.SyntaxKind.BigIntKeyword);
          }
        },
      ],
    },
    // https://heyapi.dev/openapi-ts/plugins/zod
    {
      name: "zod",
      types: {
        infer: false, // by default, no `z.infer` types
      },
      responses: {
        types: {
          infer: true, // `z.infer` types only for response schemas
        },
      },
    },
    {
      name: "@hey-api/sdk",
      // To automatically transform response data in your SDKs, set sdk.transformer to true.
      transformer: true,
      // To add data validators to your SDKs, set sdk.validator to true.
      validator: true,
      operations: {
        strategy: "single",
        containerName: "TunaBackendSdk",
      },
    },
  ],
});
