import { $, defineConfig } from "@hey-api/openapi-ts";
import ts from "typescript";

const stringIntFormats = new Set(["int64", "uint64", "int128", "uint128"]);

const stringIntToBigInt = ({ schema, dataExpression }: any) => {
  if (schema.type !== "string" || !stringIntFormats.has(schema.format)) return;

  const bigIntCall =
    dataExpression !== undefined ? $("BigInt").call($.expr(dataExpression).attr("toString").call()) : undefined;

  if (bigIntCall) {
    if (typeof dataExpression === "string") return [bigIntCall];
    return [$.expr(dataExpression).assign(bigIntCall)];
  }
};

export default defineConfig({
  input: "./openapi.camel.yaml",
  output: {
    // header: ["/* eslint-disable */", "// This file is auto-generated by @hey-api/openapi-ts"],
    path: "src/client",
  },
  plugins: [
    // ...other plugins
    // In your configuration, add @hey-api/transformers to your plugins and you'll be ready to generate transformers.
    {
      name: "@hey-api/transformers",
      dates: true,
      bigInt: true,
      transformers: [stringIntToBigInt],
      typeTransformers: [
        ({ schema }) => {
          if (schema.type === "string" && stringIntFormats.has(schema.format as string)) {
            return ts.factory.createKeywordTypeNode(ts.SyntaxKind.BigIntKeyword);
          }
        },
      ],
    },
    // To automatically transform response data in your SDKs, set sdk.transformer to true.
    {
      name: "@hey-api/sdk",
      transformer: true,
      operations: {
        strategy: "single",
      },
    },
  ],
});
